#!/usr/bin/env ruby

class GemCompletion
  def initialize(command)
    @command = command
  end
  
  def matches
    gems.select do |gem|
      gem[0, typed.length] == typed
    end
  end
  
  def typed
    @command[/\s(.+?)$/, 1] || ''
  end
  
  def gems
    `ls $(gem environment gemdir)/gems`.split
  end
end

puts GemCompletion.new(ENV["COMP_LINE"]).matches
exit 0
