#!/bin/bash

_projects()
{
    local curw
    COMPREPLY=()
    curw=${COMP_WORDS[COMP_CWORD]}
    local projects=$(ls -1 ~/code)
    COMPREPLY=($(compgen -W "$projects" -- $curw));
    return 0
}
complete -o default -F _projects c
